version: '3'

services:
  camunda_web:
    # hostname: '$NOM_DE_SOUS_DOMAINE_CAMUNDA_WEB'
    # container_name: "$NOM_CONTENEUR_CAMUNDA_WEB"
    image: poste-devops-typique:5000/pegasus-devops.io/camunda-web:0.0.1
    # image: poste-devops-typique:5000/pegasus-devops.io/camunda-web:0.0.1
    # build:
    #   context: ./docker/camunda/web/Dockerfile
      args:
        # CAMUNDA_ENV est en particulier utile pour définir une configuration de build pour la prod
        - CAMUNDA_WEB_MODELER_DOWNLOAD_URI=$CAMUNDA_WEB_MODELER_DOWNLOAD_URI
        - NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER=$NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER
        - NUM_PORT_ECOUTE_CAMUNDA_WEB=$NUM_PORT_ECOUTE_CAMUNDA_WEB
    environment:
      # CAMUNDA_ENV est en particulier utile pour définir une configuration de RUN pour la prod
      - CAMUNDA_WEB_MODELER_DOWNLOAD_URI=$CAMUNDA_WEB_MODELER_DOWNLOAD_URI
      - NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER=$NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER
    ports:
      - $NUM_PORT_ECOUTE_CAMUNDA_WEB:$NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER
    expose:
      - $NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER/tcp
    networks:
      - "$NOM_DU_RESEAU_DEMO_CAMUNDA"
      
    restart: always
#     command: yum update -y && yum install -y iputils && ping -c 4 localhost
  camunda_engine:
    # hostname: '$NOM_DE_SOUS_DOMAINE_CAMUNDA_ENGINE'
#     container_name: "$NOM_CONTENEUR_CAMUNDA_ENGINE"
    image: camunda/camunda-bpm-platform:latest
    # image: poste-devops-typique:5000/pegasus-devops.io/camunda-web:0.0.1
    # build:
    #   context: ./docker/camunda/engine/Dockerfile
      args:
        # CAMUNDA_ENV est en particulier utile pour fdéfinir une configuration de build pour la prod
        - NUM_PORT_ECOUTE_CAMUNDA_ENGINE_IN_CONTAINER=$NUM_PORT_ECOUTE_CAMUNDA_ENGINE_IN_CONTAINER
    environment:
      # CAMUNDA_ENV est en particulier utile pour définir une configuration de RUN pour la prod
      - NUM_PORT_ECOUTE_CAMUNDA_ENGINE_IN_CONTAINER=$NUM_PORT_ECOUTE_CAMUNDA_ENGINE_IN_CONTAINER
    ports:
      - $NUM_PORT_ECOUTE_CAMUNDA_ENGINE:$NUM_PORT_ECOUTE_CAMUNDA_ENGINE_IN_CONTAINER
    expose:
      - $NUM_PORT_ECOUTE_CAMUNDA_ENGINE_IN_CONTAINER/tcp
    networks:
      - "$NOM_DU_RESEAU_DEMO_CAMUNDA"
    restart: always
#     command: yum update -y && yum install -y iputils && ping -c 4 localhost 

networks:
  # donc dans le fichier ["./.env]", on doit trouver la déclaration de variable [NOM_DU_RESEAU_DEMO_CAMUNDA_JINJA2_VAR=reseau_camunda]
  NOM_DU_RESEAU_DEMO_CAMUNDA_JINJA2_VAR:
    driver: bridge
