version: '3'

services:
  camunda_modeler:
    # hostname: '$NOM_DE_SOUS_DOMAINE_CAMUNDA_WEB'
    # container_name: "$NOM_CONTENEUR_CAMUNDA_WEB"
    image: 'poste-devops-typique:5000/pegasus-devops.io/camunda-web:0.0.1'
    # image: poste-devops-typique:5000/pegasus-devops.io/camunda-web:0.0.1
    build:
      context: ./docker/camunda/modeler/
      args:
        # CAMUNDA_ENV est en particulier utile pour définir une configuration de build pour la prod
        - CAMUNDA_WEB_MODELER_GIT_SCM_URI=$CAMUNDA_WEB_MODELER_GIT_SCM_URI
        - CAMUNDA_WEB_MODELER_VERSION=$CAMUNDA_WEB_MODELER_VERSION
    environment:
      # CAMUNDA_ENV est en particulier utile pour définir une configuration de RUN pour la prod
      - CAMUNDA_WEB_MODELER_OPTIONS=$CAMUNDA_WEB_MODELER_OPTIONS
#     ports:
#       - $NUM_PORT_ECOUTE_CAMUNDA_WEB:$NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER
#     expose:
#       - $NUM_PORT_ECOUTE_CAMUNDA_WEB_IN_CONTAINER/tcp
    volumes:
      # notamment ./bpmn-modeler/camunda-modeler
      - ./bpmn-modeler:/root/modeler/:rw
    networks:
      - "$NOM_DU_RESEAU_DEMO_CAMUNDA"
    restart: always
networks:
  # donc dans le fichier ["./.env]", on doit trouver la déclaration de variable [NOM_DU_RESEAU_DEMO_CAMUNDA_JINJA2_VAR=reseau_camunda]
  NOM_DU_RESEAU_DEMO_CAMUNDA_JINJA2_VAR:
    driver: bridge
